# Generated by Django 3.1.2 on 2021-04-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210403_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_replay',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replays', to='posts.comment_replay'),
        ),
    ]
