# Generated by Django 3.1.2 on 2021-04-03 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210404_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_replay',
            name='r_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment_replay'),
        ),
    ]
